// Seed or verify the platform workspace and its default short domain.
// - Idempotent: does nothing if the workspace slug already exists.
// - Refuses to overwrite an existing workspace with the same slug.
// - Ensures the SHORT_DOMAIN exists as a Domain owned by the platform workspace.
//
// Env vars used:
// - BEYONDTC_WORKSPACE_ID: optional preferred workspace ID. If absent and
//   workspace does not exist yet, a new ID will be generated by Prisma.
// - BEYONDTC_PLATFORM_SLUG: optional, defaults to "beyondtc-platform".
// - BEYONDTC_PLATFORM_NAME: optional, defaults to "Beyond the Checkout Platform".
// - NEXT_PUBLIC_APP_SHORT_DOMAIN: required, e.g. "chko.dev" (dev), or your prod short domain.

import { config as loadEnv } from "dotenv-flow";
import path from "path";
import { prisma } from "@dub/prisma";
import { BEYONDTC_WORKSPACE_ID as CONST_WORKSPACE_ID, SHORT_DOMAIN } from "@dub/utils";

function randomPrefix(len = 8) {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let s = "";
  for (let i = 0; i < len; i++) s += alphabet[(Math.random() * alphabet.length) | 0];
  return s;
}

async function main() {
  // Resolve env files relative to DOTENV_FLOW_PATH or CWD
  const envBase = process.env.DOTENV_FLOW_PATH
    ? path.resolve(process.cwd(), process.env.DOTENV_FLOW_PATH)
    : process.cwd();
  loadEnv({ path: envBase });
  // Debug environment resolution (safe, no secrets)
  try {
    const db = process.env.DATABASE_URL ? new URL(process.env.DATABASE_URL) : null;
    console.log("Env:", {
      NODE_ENV: process.env.NODE_ENV,
      DOTENV_FLOW_PATH: envBase,
      CWD: process.cwd(),
      DB_HOST: db?.host,
      DB_NAME: db?.pathname?.slice(1),
    });
  } catch {
    // ignore
  }
  const platformSlug = process.env.BEYONDTC_PLATFORM_SLUG || "beyondtc-platform";
  const platformName = process.env.BEYONDTC_PLATFORM_NAME || "Beyond the Checkout Platform";
  const envWorkspaceId = process.env.BEYONDTC_WORKSPACE_ID || CONST_WORKSPACE_ID;
  const shortDomain = process.env.NEXT_PUBLIC_APP_SHORT_DOMAIN || SHORT_DOMAIN;

  if (!shortDomain) {
    console.error("ERROR: NEXT_PUBLIC_APP_SHORT_DOMAIN is not set.");
    process.exit(1);
  }

  console.log("Seed Platform Start", { platformSlug, platformName, shortDomain });

  // 1) Find or create the platform workspace by slug
  let platform = await prisma.project.findUnique({ where: { slug: platformSlug } });

  if (platform) {
    console.log(`Workspace already exists: ${platformSlug} (id=${platform.id})`);
  } else {
    console.log(`Creating platform workspace: ${platformSlug}`);
    try {
      platform = await prisma.project.create({
        data: {
          // Use the env-provided ID if it's non-empty and not "undefined"
          ...(envWorkspaceId && envWorkspaceId !== "undefined" && { id: envWorkspaceId }),
          name: platformName,
          slug: platformSlug,
          billingCycleStart: new Date().getDate(),
          invoicePrefix: randomPrefix(8),
          inviteCode: null,
          defaultDomains: { create: {} },
        },
      });
      console.log(`Created workspace id=${platform.id}`);
      if (!process.env.BEYONDTC_WORKSPACE_ID) {
        console.log("Note: Set BEYONDTC_WORKSPACE_ID to this id in your env for consistency.");
      }
    } catch (e: any) {
      if (e?.code === "P2002") {
        console.error(`Refusing to overwrite existing slug: ${platformSlug}`);
      } else {
        console.error("Failed to create platform workspace:", e);
      }
      process.exit(1);
    }
  }

  // 2) Ensure SHORT_DOMAIN exists as a Domain owned by the platform workspace
  const existingDomain = await prisma.domain.findUnique({ where: { slug: shortDomain } });

  if (existingDomain) {
    if (existingDomain.projectId !== platform.id) {
      console.error(
        `Domain ${shortDomain} already exists and belongs to a different workspace (${existingDomain.projectId}).` +
          "\nRefusing to reassign. Please resolve manually.",
      );
      process.exit(1);
    }
    console.log(`Domain already present: ${shortDomain}`);
  } else {
    console.log(`Creating domain: ${shortDomain}`);
    await prisma.domain.create({
      data: {
        slug: shortDomain,
        projectId: platform.id,
        primary: true,
      },
    });
    console.log(`Created domain: ${shortDomain}`);
  }

  // 3) Ensure root link exists for the domain
  const rootLink = await prisma.link.findUnique({
    where: { domain_key: { domain: shortDomain, key: "_root" } },
    select: { id: true },
  });

  if (rootLink) {
    console.log("Root link exists for domain.");
  } else {
    console.log("Creating root link for domain.");
    await prisma.link.create({
      data: {
        domain: shortDomain,
        key: "_root",
        url: "",
        shortLink: `https://${shortDomain}/_root`,
        projectId: platform.id,
      },
    });
    console.log("Created root link.");
  }

  console.log("Seed Platform Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
